const state = { questions: [], filtered: [], index: 0, selected: null, submitted: false, deck: 'all', level: 'all', search: '', stats: JSON.parse(localStorage.getItem('knovatrix-quiz-stats') || '{"answered":0,"correct":0,"sessions":0}') };
const root = document.querySelector('#app');
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));
const adSlot = () => '<div class="ad-slot" aria-label="廣告位置">廣告位置（接入廣告平台後顯示）</div>';
const values = key => [...new Set(state.questions.map(question => question[key]))].sort();
function syncQuestions() { state.filtered = state.questions.filter(question => (state.level === 'all' || question.level === state.level) && (state.deck === 'all' || question.deck === state.deck) && (!state.search || (question.prompt + ' ' + question.subject + ' ' + question.source).toLowerCase().includes(state.search.toLowerCase()))); }
function saveStats() { localStorage.setItem('knovatrix-quiz-stats', JSON.stringify(state.stats)); }
function renderHome() {
  const decks = values('deck');
  const levels = values('level');
  const cards = decks.filter(deck => state.deck === 'all' || deck === state.deck).map(deck => {
    const amount = state.filtered.filter(question => question.deck === deck).length;
    const sample = state.filtered.find(question => question.deck === deck);
    return `<a class="deck" href="#/quiz?deck=${encodeURIComponent(deck)}"><span class="badge">${escapeHtml(sample?.level || '題組')}</span><h3>${escapeHtml(deck)}</h3><p>${amount} 題 · 可隨時中斷</p><small>開始練習 →</small></a>`;
  }).join('');
  root.innerHTML = `<section class="hero"><div><p class="eyebrow">MOBILE PRACTICE</p><h1>把零碎時間，變成一題一題的進步。</h1><p class="lead">從數學、自然到競賽基礎，選一個題組就能開始練習。答題結果只保存在你的裝置上。</p></div>${adSlot()}</section><div class="filterbar"><div class="field"><label for="level">學段</label><select id="level"><option value="all">全部學段</option>${levels.map(level => `<option value="${escapeHtml(level)}">${escapeHtml(level)}</option>`).join('')}</select></div><div class="field"><label for="deck">題組</label><select id="deck"><option value="all">全部題組</option>${decks.map(deck => `<option value="${escapeHtml(deck)}">${escapeHtml(deck)}</option>`).join('')}</select></div></div><div class="field"><label for="search">搜尋題組或主題</label><input id="search" placeholder="例如：因數、細胞、力學"></div><div class="section-head"><div><h2>開始練習</h2><p>${state.filtered.length} 題可用</p></div></div><div class="deck-grid">${cards}</div>`;
  document.querySelector('#level').value = state.level; document.querySelector('#deck').value = state.deck; document.querySelector('#search').value = state.search;
  document.querySelector('#level').onchange = event => { state.level = event.target.value; syncQuestions(); renderHome(); };
  document.querySelector('#deck').onchange = event => { state.deck = event.target.value; syncQuestions(); renderHome(); };
  document.querySelector('#search').oninput = event => { state.search = event.target.value; syncQuestions(); renderHome(); };
}
function renderQuiz() {
  const question = state.filtered[state.index];
  if (!question) { root.innerHTML = '<div class="empty">目前找不到符合條件的題目。<br><a class="button secondary" href="#/">返回題組</a></div>'; return; }
  const correct = String(state.selected) === String(question.answer);
  const answerArea = question.type === 'short' ? `<input class="field" id="short-answer" inputmode="numeric" placeholder="輸入答案" value="${escapeHtml(state.selected || '')}">` : question.options.map((option, index) => `<label class="choice ${state.submitted && index === question.answer ? 'correct' : ''} ${state.submitted && state.selected === index && index !== question.answer ? 'wrong' : ''} ${state.selected === index ? 'selected' : ''}"><input type="radio" name="answer" value="${index}" ${state.selected === index ? 'checked' : ''} ${state.submitted ? 'disabled' : ''}>${escapeHtml(option)}</label>`).join('');
  root.innerHTML = `<div class="quiz-shell"><section><div class="quiz-header"><div><p class="eyebrow">${escapeHtml(question.deck)}</p><h1>第 ${state.index + 1} 題</h1></div><span class="progress">${state.index + 1} / ${state.filtered.length}</span></div><article class="question-card"><div class="question-meta"><span>${escapeHtml(question.subject || '綜合')}</span><span>${question.type === 'short' ? '填充題' : '選擇題'}</span></div><div class="question-text">${escapeHtml(question.prompt)}</div><div class="choices">${answerArea}</div><div class="answer-row"><button class="button" id="submit" ${state.submitted ? 'disabled' : ''}>確認答案</button><button class="button secondary" id="next" ${state.submitted ? '' : 'disabled'}>${state.index === state.filtered.length - 1 ? '完成' : '下一題'}</button></div>${state.submitted ? `<div class="feedback ${correct ? 'ok' : 'no'}"><strong>${correct ? '答對了！' : '再想一下'}</strong><span>${escapeHtml(question.explanation || '先回看題目條件，再找出關鍵關係。')}</span></div>` : ''}</article></section><aside class="quiz-side"><div class="side-panel"><h3>本次進度</h3><div class="score">${state.stats.correct} <small>/ ${state.stats.answered}</small></div><p>累積答對題數</p></div>${adSlot()}<div class="side-panel"><h3>來源</h3><p>${escapeHtml(question.source || 'Knovatrix 題庫')}</p></div></aside></div>`;
  document.querySelectorAll('input[name="answer"]').forEach(input => input.onchange = () => { state.selected = Number(input.value); document.querySelectorAll('.choice').forEach(choice => choice.classList.remove('selected')); input.closest('.choice').classList.add('selected'); });
  const shortAnswer = document.querySelector('#short-answer'); if (shortAnswer) shortAnswer.oninput = event => { state.selected = event.target.value; };
  document.querySelector('#submit').onclick = () => { if (state.selected === null || state.selected === '') return; state.submitted = true; state.stats.answered += 1; if (correct) state.stats.correct += 1; saveStats(); renderQuiz(); };
  document.querySelector('#next').onclick = () => { if (!state.submitted) return; if (state.index < state.filtered.length - 1) { state.index += 1; state.selected = null; state.submitted = false; renderQuiz(); } else { state.stats.sessions += 1; saveStats(); location.hash = '/progress'; } };
}
function renderProgress() { const percentage = state.stats.answered ? Math.round(state.stats.correct / state.stats.answered * 100) : 0; root.innerHTML = `<section class="hero"><div><p class="eyebrow">YOUR PROGRESS</p><h1>學習紀錄</h1><p class="lead">答題統計保存在目前裝置，不需要登入。</p></div>${adSlot()}</section><div class="history"><div class="history-item"><span>累積作答</span><b>${state.stats.answered} 題</b></div><div class="history-item"><span>答對題數</span><b>${state.stats.correct} 題（${percentage}%）</b></div><div class="history-item"><span>完成題組</span><b>${state.stats.sessions} 次</b></div></div><div class="answer-row"><button class="button secondary" id="reset">清除本機紀錄</button><a class="button" href="#/">繼續練習</a></div>`; document.querySelector('#reset').onclick = () => { if (confirm('確定清除這台裝置的刷題紀錄？')) { state.stats = { answered: 0, correct: 0, sessions: 0 }; saveStats(); renderProgress(); } }; }
function route() { const parts = location.hash.slice(1).split('?'); const params = new URLSearchParams(parts[1] || ''); if (parts[0] === '/quiz') { state.deck = params.get('deck') || 'all'; syncQuestions(); state.index = 0; state.selected = null; state.submitted = false; renderQuiz(); } else if (parts[0] === '/progress') renderProgress(); else renderHome(); }
window.addEventListener('hashchange', route); fetch('data/questions.json').then(response => response.json()).then(data => { state.questions = data; syncQuestions(); route(); }).catch(() => { root.innerHTML = '<div class="empty">題庫資料載入失敗，請稍後再試。</div>'; });
